language: python
python:
    - "3.4"
    - "3.5"
addons:
    apt:
        packages:
            - build-essential
            - libatlas-dev
            - libatlas3g-base # Should be libatlas3gf-base.
            - python3-dev
            - python3-setuptools
            - python3-numpy
            - python3-scipy
install:
    - pip3 install scikit-learn
    - make
script:
    - cd app/test
    - py.test-3

