language: python
python:
    - "3.4"
    - "3.5"
addons:
    apt:
        packages:
            - build-essential
            - libatlas-dev
            - liblapack-dev
            - gfortran
            - python3-dev
            - python3-numpy
            - python3-scipy
before_install:
    - pip install -U pip setuptools wheel
install:
    - travis_wait travis_retry pip install -r requirements.txt
    - make
script:
    - cd app/test
    - py.test
notifications:
    slack: io-touchpad:Fv8xkXiL4PSbXN8GN9hDAlxp
    email: false
