language: python
sudo: false
python:
    - "3.4"
    - "3.5"
addons:
    apt:
        packages:
            - libatlas-dev
            - liblapack-dev
            - gfortran
before_install:
    - pip install -U pip setuptools wheel pytest-cov
install:
    # - pip install coveralls
    - pip install codecov
    - travis_wait travis_retry pip install -r requirements.txt
    - make
script:
    - cd app/test
    - py.test --cov=./
notifications:
    slack: io-touchpad:Fv8xkXiL4PSbXN8GN9hDAlxp
    email: false
after_success:
    - bash <(curl -s https://codecov.io/bash)
